using System.Text;
using ChocolateyPackageBuilder.Core.Interfaces;
using ChocolateyPackageBuilder.Core.Models;

namespace ChocolateyPackageBuilder.Core.Generators;

public sealed class CustomInstallerScriptGenerator : ICustomInstallerScriptGenerator
{
    public string Generate(CustomInstallerProject project)
    {
        ArgumentNullException.ThrowIfNull(project);

        var builder = new StringBuilder();
        builder.AppendLine("# ==============================================================================");
        builder.AppendLine("# This script was generated by ChocolateyPackageBuilder");
        builder.AppendLine("# ==============================================================================");
        builder.AppendLine();
        builder.AppendLine("$ErrorActionPreference = 'Stop';");
        builder.AppendLine("$toolsDir     = $(Split-Path -parent $MyInvocation.MyCommand.Definition)");
        builder.AppendLine();
        builder.AppendLine("$projectFiles = @{");
        foreach (var file in project.Files)
            builder.Append("  '").Append(Escape(file.Id)).Append("' = '")
                .Append(Escape(ToPackagePath(file.PackagePath))).AppendLine("'");

        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("function Resolve-CpbPath([string]$kind, [string]$value) {");
        builder.AppendLine("  if ($kind -eq 'PackageFile') {");
        builder.AppendLine(
            "    if (-not $projectFiles.ContainsKey($value)) { throw \"Unknown project file id: $value\" }");
        builder.AppendLine("    return Join-Path $toolsDir $projectFiles[$value]");
        builder.AppendLine("  }");
        builder.AppendLine("  if ($kind -eq 'Literal') { return [Environment]::ExpandEnvironmentVariables($value) }");
        builder.AppendLine("  throw \"Unknown action path kind: $kind\"");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("function Assert-CpbValidExitCode([int]$exitCode, [int[]]$validExitCodes, [string]$file) {");
        builder.AppendLine(
            "  if ($validExitCodes -notcontains $exitCode) { throw \"Process '$file' exited with code $exitCode.\" }");
        builder.AppendLine("}");
        builder.AppendLine();

        for (var i = 0; i < project.Actions.Count; i++)
        {
            var action = project.Actions[i];
            builder.AppendLine($"# Action {i + 1}: {action.Kind}");
            switch (action.Kind)
            {
                case InstallActionKind.CopyFile:
                    AppendCopyFile(builder, action);
                    break;
                case InstallActionKind.RunFile:
                    AppendRunFile(builder, action);
                    break;
                default:
                    throw new InvalidOperationException($"Unsupported install action kind: {action.Kind}.");
            }

            builder.AppendLine();
        }

        return builder.ToString();
    }

    private void AppendCopyFile(StringBuilder builder, InstallAction action)
    {
        builder.AppendLine($"$source = Resolve-CpbPath '{action.Source.Kind}' '{Escape(action.Source.Value)}'");
        builder.AppendLine(
            $"$destination = Resolve-CpbPath '{action.Destination.Kind}' '{Escape(action.Destination.Value)}'");
        builder.AppendLine("$destinationParent = Split-Path -Parent $destination");
        builder.AppendLine(
            "if (-not [string]::IsNullOrWhiteSpace($destinationParent)) { New-Item -ItemType Directory -Path $destinationParent -Force | Out-Null }");
        if (action.Overwrite)
        {
            builder.AppendLine("Copy-Item -LiteralPath $source -Destination $destination -Force");
        }
        else
        {
            builder.AppendLine(
                "if (Test-Path -LiteralPath $destination) { throw \"Destination already exists: $destination\" }");
            builder.AppendLine("Copy-Item -LiteralPath $source -Destination $destination");
        }
    }

    private void AppendRunFile(StringBuilder builder, InstallAction action)
    {
        builder.AppendLine($"$file = Resolve-CpbPath '{action.File.Kind}' '{Escape(action.File.Value)}'");
        if (action.WaitForExit)
        {
            builder.Append("$process = Start-Process -FilePath $file");
            AppendArgumentList(builder, action.Arguments);
            builder.AppendLine(" -Wait -PassThru");
            var validExitCodes = action.ValidExitCodes is { Count: > 0 } ? action.ValidExitCodes : [0];
            builder.AppendLine(
                $"Assert-CpbValidExitCode $process.ExitCode @({string.Join(", ", validExitCodes)}) $file");
        }
        else
        {
            builder.Append("Start-Process -FilePath $file");
            AppendArgumentList(builder, action.Arguments);
            builder.AppendLine();
        }
    }

    private void AppendArgumentList(StringBuilder builder, string arguments)
    {
        if (!string.IsNullOrWhiteSpace(arguments))
            builder.Append(" -ArgumentList '").Append(Escape(arguments)).Append("'");
    }

    private string Escape(string value)
    {
        return value.Replace("'", "''", StringComparison.Ordinal);
    }

    private string ToPackagePath(string value)
    {
        return value.Replace('/', '\\');
    }
}