namespace ChocolateyPackageBuilder.Core;

public static class ScriptGenerator
{
    public static string Generate(InstallerType type, string packageName, string installerFileName)
    {
        var isScaffold = type == InstallerType.Unknown;

        string silentArgs;
        var fileType = "exe";

        switch (type)
        {
            case InstallerType.Msi:
                silentArgs = "'/qn /norestart'";
                fileType = "msi";
                break;
            case InstallerType.InnoSetup:
                silentArgs = "'/VERYSILENT /SUPPRESSMSGBOXES /NORESTART'";
                break;
            case InstallerType.Nsis:
                silentArgs = "'/S'";
                break;
            case InstallerType.Unknown:
            default:
                silentArgs = "'/S' # TODO: Verify or update these silent arguments";
                break;
        }

        return $$"""
                 # ==============================================================================
                 # This script was generated by ChocolateyPackageBuilder
                 # ==============================================================================

                 $ErrorActionPreference = 'Stop';
                 $toolsDir     = $(Split-Path -parent $MyInvocation.MyCommand.Definition)
                 $fileLocation = Join-Path $toolsDir '{{installerFileName}}'

                 $packageArgs = @{
                   packageName   = '{{packageName}}'
                   unzipLocation = $toolsDir
                   fileType      = '{{fileType}}'
                   file          = $fileLocation
                   silentArgs    = {{silentArgs}}
                   validExitCodes= @(0{{(isScaffold ? ", 1641, 3010 # TODO: Verify exit codes" : "")}})
                   softwareName  = '{{packageName}}'
                 }

                 Install-ChocolateyInstallPackage @packageArgs

                 """;
    }
}